### ISSUE TITLE
How can I enable this cheat?

### ISSUE THREAD

**Issue by nxstd** [Giovanifsa/AssaultCubeTrainerLinux#2]
I really don't know how to use it ...
I tried every possible key, but I didn't see any result.

Could this issue be related to the game version or not?
Was I doing something wrong?

@Giovanifsa @rafaelrc7

**Comment by Giovanifsa** [comment]
Hello @hilight3r, for now, this project is just a prototype and not in a working state. You may load it by running inject.sh, but be aware that there are no functionalities just yet. You may find another prototype (but for Windows) that has some functionalities here: https://github.com/Giovanifsa/AssaultCubeTrainer

**Comment by nxstd** [comment]
Thanks!
